version: '3'

services:
  springboot-docker-compose-app-container:
    image: invisible-pay-docker-compose-app:1
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      TZ: "Europe/Berlin"
    volumes:
      - /data/invisible-pay-docker-compose-app
    ports:
      - "8081:8081"